# 1.Print 'Hello HCIA'.

In [ ]:
print('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [ ]:
A = 6
B = 7
print(A + B)

13


# 3.Define a list and replicate in three different ways.

In [ ]:
my_list = [1, 0, 6]
new_list1 = my_list.copy()
print(new_list1)
new_list2 = my_list[:]
print(new_list2)
new_list3 = []
for i in my_list:
  new_list3.append(i)
print(new_list3)

#неточная формулировка, поэтому есть два варианта вывода
#второй вариант:

l = [1, 2, 3, 5, 7, 9, 0]
print(l,l,l)
for i in range(3):
print(l)
print([l]*3)

[1, 0, 6]
[1, 0, 6]
[1, 0, 6]


# 4.Define two lists and merge them together.

In [ ]:
l1 = [0, 1, 2]
l2 = [3, 4, 5]
lis = l1 + l2
print(lis)

[0, 1, 2, 3, 4, 5]


# 5. Get the last element of the list and print it.

In [ ]:
my_list = [0, 1, 2, 4]
print(my_list[len(my_list)-1])

4


# 6.Define a tuple that contains only one element.

In [ ]:
a = tuple([1])
print(a)
print(type(a))

(1,)
<class 'tuple'>


# 7.Define a three-line long string.

In [ ]:
s = "cute \nlittle \nbunny"
print(s)

cute 
little 
bunny


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [ ]:
t = ([1], [2], [3])
for x in t:
  print(x)

<class 'tuple'>
[1]
[2]
[3]


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [ ]:
def mul(a, b):
  return a*b 
mul(8, 6)

48

# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [ ]:
import numpy as np
s = (5, 5)
np.zeros(s)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [ ]:
import numpy as np
s = (4, 6)
np.zeros(s)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [44]:
a = np.arange(15)
print(a.shape)
print(a.reshape(3, 5))


(15,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [48]:
a = np.array([[2, 0],
[1, 1]])
b = np.array([[3, 1], [2, 2]])
print(np.matmul(a, b))

#второй вариант решения:

a = np.array([ [2, 0], [1, 1]])
b = np.array([[3,1], [2,2]])
total = a.dot(b)
print(total)

[[6 2]
 [5 3]]
[[6 2]
 [5 3]]
